// examples/next/app/dashboard/page.tsx
//
// tasks.md 8.3: the real REQ-SSR entry point — a `<Suspense>` boundary whose
// fallback is `<AutoSkeleton.SSR>` (imported from the `autoskeleton/ssr`
// subpath, NFR-6 §index.web.ts's doc comment), replaying the build-time
// capture for `skeletonKey="dashboard"` instead of attempting any live
// layout detection (REQ-SSR-1). `manifest` is a plain JSON import — the
// capture CLI's output, regenerated by `test/ssr/*.spec.ts`'s setup before
// this route is ever requested in the SSR test suite.

import { Suspense } from 'react';
import { AutoSkeletonSSR } from 'autoskeleton/ssr';
import { manifest } from '../../generated/autoskeleton-ssr';
import { DashboardContent } from './DashboardContent';

// Forces per-request dynamic rendering: without this, Next.js resolves the
// Suspense boundary AT BUILD TIME and serves fully-static HTML with the
// fallback never appearing at request time at all — which would make this
// route unable to prove anything about REQ-SSR-1/REQ-SSR-4 (there would be
// no fallback to inspect, no streaming, nothing to hydrate).
export const dynamic = 'force-dynamic';

export default function DashboardPage() {
  return (
    <Suspense fallback={<AutoSkeletonSSR skeletonKey="dashboard" manifest={manifest} direction="ltr" />}>
      <DashboardContent />
    </Suspense>
  );
}
